# Generated by Django 5.0.3 on 2024-03-09 10:28

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models

import backend.user_profile.utils.save_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True,
                 upload_to=backend.user_profile.utils.save_file.avatar_path, verbose_name='аватар')),
                ('deleted', models.BooleanField(choices=[(True, 'Удалено'),
                 (False, 'Активно')], default=False, verbose_name='статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
                'db_table': 'profile',
            },
        ),
    ]
